/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "log.h"


/* Header for class com_jeanboy_demo_jnitest_NdkTest */

#ifndef _Included_com_commax_sqlitejnitest_SqliteJNIManager
#define _Included_com_commax_sqlitejnitest_SqliteJNIManager
#ifdef __cplusplus
extern "C" {
#endif


JNIEXPORT void JNICALL Java_com_commax_sqlitejnitest_SqliteJNIManager_readAllDevices
        (JNIEnv *, jclass);
/*
 * Class:     com_jeanboy_demo_jnitest_NdkTest
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_com_commax_sqlitejnitest_SqliteJNIManager_addDeviceToDB
  (JNIEnv *, jclass);

/*
 * Class:     com_jeanboy_demo_jnitest_NdkTest
 * Method:    doAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_commax_sqlitejnitest_SqliteJNIManager_removeDeviceOnDB
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
